const headphones = [
    {
        id: 'h1',
        img: '../images/h1.jpg',
        title: 'Apple BYZ S852I',
        priceNew: '2927',
        priceOld: '3527',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'h2',
        img: '../images/h2.jpg',
        title: 'Apple EarPods',
        priceNew: '2327',
        priceOld: '',
        rate: '4.5',
        quantity: 0,
    },
    {
        id: 'h3',
        img: '../images/h3.jpg',
        title: 'Apple EarPods',
        priceNew: '2327',
        priceOld: '',
        rate: '4.5',
        quantity: 0,
    },
    {
        id: 'h4',
        img: '../images/h1.jpg',
        title: 'Apple BYZ S852I',
        priceNew: '2927',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'h5',
        img: '../images/h2.jpg',
        title: 'Apple EarPods',
        priceNew: '2327',
        priceOld: '',
        rate: '4.5',
        quantity: 0,
    },
    {
        id: 'h6',
        img: '../images/h3.jpg',
        title: 'Apple EarPods',
        priceNew: '2327',
        priceOld: '',
        rate: '4.5',
        quantity: 0,
    },
    {
        id: 'hw1',
        img: '../images/hw1.jpg',
        title: 'Apple AirPods',
        priceNew: '9527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'hw2',
        img: '../images/hw2.jpg',
        title: 'GERLAX GH-04',
        priceNew: '6527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'hw3',
        img: '../images/hw3.jpg',
        title: 'BOROFONE BO4',
        priceNew: '7527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
]
const headphonesWireless = [
    {
        id: 'hw1',
        img: '../images/hw1.jpg',
        title: 'Apple AirPods',
        priceNew: '9527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'hw2',
        img: '../images/hw2.jpg',
        title: 'GERLAX GH-04',
        priceNew: '6527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
    {
        id: 'hw3',
        img: '../images/hw3.jpg',
        title: 'BOROFONE BO4',
        priceNew: '7527',
        priceOld: '',
        rate: '4.7',
        quantity: 0,
    },
]

export {headphones, headphonesWireless}